### ISSUE TITLE
Memory leak in GetGlobalDomainDefaultInstance function

### ISSUE THREAD

**Issue by enum-class** [google/fuzztest#77]
Hello, I have seen a memory leak in GetGlobalDomainDefaultInstance method in [domain.h](https://github.com/google/fuzztest/blob/18f1083f8a2ae5b91aff16dcf42929df8173c6be/fuzztest/internal/domain.h#L2441).

In that function it allocates Domain<T> in heap by calling new, and never delete that. maybe it can be solved by using smart pointers.

**Comment by fniksic** [comment]
Hey, sorry, I forgot to answer to this earlier.

This is a benign leak, since the pointer is a variable with static duration. The memory is allocated until the program terminates, and then it is reclaimed by the OS.

Deleting the memory (either directly or through a smart pointer) would actually be a mistake, because it would potentially introduce a race condition and heap-use-after-free issues.
